modmap:
  - name: all
    device:
      only: "AT Translated Set 2 keyboard"
    remap:
      CapsLock: Control_L
      Alt_R: CapsLock

keymap:
  - name: non_term
    device:
      only: "AT Translated Set 2 keyboard"
    remap:
      M-l: right
      M-h: left
      M-k: up
      M-j: down
      M-e: end
      M-backspace: C-backspace
      M-f: C-right
      M-b: C-left
      M-0: F9
      M-9: F8
      M-q: delete
      M-1: F1
      M-2: F2
      M-3: F3
      M-4: F4
      M-t: F12
      M-d: C-x
      M-p: C-v
      M-y: C-c
      M-u: [Home, S-End]


  - name: term
    application:
      only: [Alacritty]
    remap:
      C-backspace: C-w

